import 'package:flutter/material.dart';

/// 16x16 pixel-art icons drawn from character maps (no bitmap assets).
enum PixelIcon {
  folder,
  folderOpen,
  removableDrive,
  hardDrive,
  computer,
  imageFile,
  videoFile,
  hourglass,
  eject,
  upFolder,
  delete,
  info,
  warning,
  error,
  question,
  views,
  camera,
  lock,
  floppy,
  transfer,

  /// The Darkroom rabbit, RGB-split like the app icon.
  rabbit,
}

class PixelIconView extends StatelessWidget {
  const PixelIconView(this.icon, {super.key, this.size = 16});

  final PixelIcon icon;
  final double size;

  @override
  Widget build(BuildContext context) {
    return CustomPaint(size: Size.square(size), painter: _SpritePainter(_sprites[icon]!));
  }
}

const _palette = <String, Color>{
  'k': Color(0xFF000000),
  'w': Color(0xFFFFFFFF),
  'g': Color(0xFF808080),
  'l': Color(0xFFC0C0C0),
  'y': Color(0xFFFFFF00),
  'o': Color(0xFF808000),
  'b': Color(0xFF0000FF),
  'n': Color(0xFF000080),
  'c': Color(0xFF00FFFF),
  't': Color(0xFF008080),
  'r': Color(0xFFFF0000),
  'm': Color(0xFF800000),
  'G': Color(0xFF00FF00),
  'd': Color(0xFF008000),
};

class _SpritePainter extends CustomPainter {
  const _SpritePainter(this.rows);

  final List<String> rows;

  @override
  void paint(Canvas canvas, Size size) {
    final px = size.width / 16;
    final paint = Paint()..isAntiAlias = false;
    for (var y = 0; y < rows.length; y++) {
      final row = rows[y];
      for (var x = 0; x < row.length; x++) {
        final c = _palette[row[x]];
        if (c == null) continue;
        paint.color = c;
        canvas.drawRect(Rect.fromLTWH(x * px, y * px, px + 0.01, px + 0.01), paint);
      }
    }
  }

  @override
  bool shouldRepaint(_SpritePainter old) => !identical(old.rows, rows);
}

/// Every row is exactly 16 characters ('.' = transparent).
const Map<PixelIcon, List<String>> _sprites = {
  PixelIcon.folder: [
    '................',
    '................',
    '..kkkkk.........',
    '.kywyyyk........',
    'kywyyyyykkkkkkk.',
    'kwyyyyyyyyyyyyok',
    'kyyyyyyyyyyyyyok',
    'kyyyyyyyyyyyyyok',
    'kyyyyyyyyyyyyyok',
    'kyyyyyyyyyyyyyok',
    'kyyyyyyyyyyyyyok',
    'kyyyyyyyyyyyyyok',
    'kyyyyyyyyyyyyyok',
    'kooooooooooooook',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  PixelIcon.folderOpen: [
    '................',
    '................',
    '..kkkkk.........',
    '.kywyyyk........',
    'kywyyyyykkkkkk..',
    'kwyyyyyyyyyyyok.',
    'kyyykkkkkkkkkkkk',
    'kyykwyyyyyyyyyyk',
    'kyykyyyyyyyyyyok',
    'kykwyyyyyyyyyok.',
    'kykyyyyyyyyyyok.',
    'kkwyyyyyyyyyok..',
    'kkyyyyyyyyyyok..',
    'kooooooooooook..',
    '.kkkkkkkkkkkk...',
    '................',
  ],
  PixelIcon.removableDrive: [
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwwk.',
    '.kwllllllllllgk.',
    '.kwlkkkkkkkklgk.',
    '.kwllllllllllgk.',
    '.kwlllllllldlgk.',
    '.kwllllllllGlgk.',
    '.kggggggggggggk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  PixelIcon.hardDrive: [
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwwk.',
    '.kwllllllllllgk.',
    '.kwllllllllllgk.',
    '.kwllllllllllgk.',
    '.kwlllllllllGgk.',
    '.kggggggggggggk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
  ],
  PixelIcon.computer: [
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwgk.',
    '.kwkkkkkkkkkwgk.',
    '.kwkttttttttwgk.',
    '.kwkttcttttttgk.',
    '.kwktttttttkwgk.',
    '.kwkttttttttwgk.',
    '.kwkkkkkkkkkwgk.',
    '.kwwwwwwwwwwwgk.',
    '.kggggggggggggk.',
    '..kkkkkkkkkkkk..',
    '....kgggggggk...',
    '..kkwwwwwwwwwkk.',
    '.kwllllllllllgk.',
    '.kggggggggggggk.',
    '..kkkkkkkkkkkk..',
  ],
  PixelIcon.imageFile: [
    '..kkkkkkkkk.....',
    '..kwwwwwwwkk....',
    '..kwwwwwwwkwk...',
    '..kwwwwwwwkkkk..',
    '..kwccccccccwk..',
    '..kwccccccycwk..',
    '..kwcccccyyywk..',
    '..kwccccccycwk..',
    '..kwccdcccccwk..',
    '..kwcdddccdcwk..',
    '..kwddddddddwk..',
    '..kwddddddddwk..',
    '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  PixelIcon.videoFile: [
    '..kkkkkkkkk.....',
    '..kwwwwwwwkk....',
    '..kwwwwwwwkwk...',
    '..kwwwwwwwkkkk..',
    '..kwkkkkkkkkwk..',
    '..kwkwkwkwkwwk..',
    '..kwkkkkkkkkwk..',
    '..kwknnnnnnkwk..',
    '..kwknbbbbnkwk..',
    '..kwknnnnnnkwk..',
    '..kwkkkkkkkkwk..',
    '..kwkwkwkwkwwk..',
    '..kwkkkkkkkkwk..',
    '..kwwwwwwwwwwk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  PixelIcon.hourglass: [
    '................',
    '...kkkkkkkkkk...',
    '...kllllllllk...',
    '....kwwwwwwk....',
    '....kwyyyywk....',
    '.....kwyywk.....',
    '......kyyk......',
    '.......kk.......',
    '.......kk.......',
    '......kwwk......',
    '.....kwwywk.....',
    '....kwwyyywk....',
    '....kwyyyyyk....',
    '...kllllllllk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  PixelIcon.eject: [
    '................',
    '................',
    '................',
    '.......kk.......',
    '......kkkk......',
    '.....kkkkkk.....',
    '....kkkkkkkk....',
    '...kkkkkkkkkk...',
    '..kkkkkkkkkkkk..',
    '................',
    '..kkkkkkkkkkkk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
  ],
  PixelIcon.upFolder: [
    '................',
    '................',
    '..kkkkk.........',
    '.kywyyyk........',
    'kywyyyyykkkkkkk.',
    'kwyyyyykyyyyyyok',
    'kyyyyykkkyyyyyok',
    'kyyyykkkkkyyyyok',
    'kyyyyyykyyyyyyok',
    'kyyyyyykyyyyyyok',
    'kyyyyyykkkkkyyok',
    'kyyyyyyyyyyyyyok',
    'kyyyyyyyyyyyyyok',
    'kooooooooooooook',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  PixelIcon.delete: [
    '................',
    '................',
    '..rr........rr..',
    '..rrr......rrr..',
    '...rrr....rrr...',
    '....rrr..rrr....',
    '.....rrrrrr.....',
    '......rrrr......',
    '......rrrr......',
    '.....rrrrrr.....',
    '....rrr..rrr....',
    '...rrr....rrr...',
    '..rrr......rrr..',
    '..rr........rr..',
    '................',
    '................',
  ],
  PixelIcon.info: [
    '.....kkkkkk.....',
    '...kkwwwwwwkk...',
    '..kwwwwwwwwwwk..',
    '.kwwwwwbbwwwwwk.',
    '.kwwwwwbbwwwwwk.',
    'kwwwwwwwwwwwwwwk',
    'kwwwwwbbbwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    '.kwwwwwbbwwwwwk.',
    '.kwwwwbbbbwwwwk.',
    '..kwwwwwwwwwwk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '................',
  ],
  PixelIcon.warning: [
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kyyyyk.....',
    '.....kykkyk.....',
    '....kyykkyyk....',
    '....kyykkyyk....',
    '...kyyykkyyyk...',
    '...kyyykkyyyk...',
    '..kyyyykkyyyyk..',
    '..kyyyyyyyyyyk..',
    '.kyyyyykkyyyyyk.',
    '.kyyyyykkyyyyyk.',
    'kyyyyyyyyyyyyyyk',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  PixelIcon.error: [
    '.....kkkkkk.....',
    '...kkrrrrrrkk...',
    '..krrrrrrrrrrk..',
    '.krrwrrrrrrwrrk.',
    '.krwwwrrrrwwwrk.',
    'krrrwwwrrwwwrrrk',
    'krrrrwwwwwwrrrrk',
    'krrrrrwwwwrrrrrk',
    'krrrrrwwwwrrrrrk',
    'krrrrwwwwwwrrrrk',
    '.krrwwwrrwwwrrk.',
    '.krwwwrrrrwwwrk.',
    '..krrrrrrrrrrk..',
    '...kkrrrrrrkk...',
    '.....kkkkkk.....',
    '................',
  ],
  PixelIcon.question: [
    '.....kkkkkk.....',
    '...kkwwwwwwkk...',
    '..kwwwbbbbwwwk..',
    '.kwwwbbwwbbwwwk.',
    '.kwwwwwwwbbwwwk.',
    'kwwwwwwwbbwwwwwk',
    'kwwwwwwbbwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    'kwwwwwwwwwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    '.kwwwwwbbwwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '..kwwwwwwwwwwk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '................',
  ],
  PixelIcon.views: [
    '................',
    '.kkkk.kkkk.kkkk.',
    '.kcck.kcck.kcck.',
    '.kcck.kcck.kcck.',
    '.kkkk.kkkk.kkkk.',
    '................',
    '.kkkk.kkkk.kkkk.',
    '.kcck.kcck.kcck.',
    '.kcck.kcck.kcck.',
    '.kkkk.kkkk.kkkk.',
    '................',
    '.kkkk.kkkk.kkkk.',
    '.kcck.kcck.kcck.',
    '.kcck.kcck.kcck.',
    '.kkkk.kkkk.kkkk.',
    '................',
  ],
  PixelIcon.camera: [
    '................',
    '................',
    '................',
    '.....kkkk.......',
    '.kkkkllllkkkkkk.',
    '.kwwwwwwwwwwwwk.',
    '.kwllkkkkkllrlk.',
    '.kwlkgnngklllgk.',
    '.kwlkncbnklllgk.',
    '.kwlknbnnklllgk.',
    '.kwlkgnngklllgk.',
    '.kwllkkkkklllgk.',
    '.kggggggggggggk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  PixelIcon.rabbit: [
    '................',
    '..rwwb..........',
    '..rwwb..rwwb....',
    '..rwwb..rwwwwb..',
    '..rwwb..rwwwwwb.',
    '...rwwbrwwb.....',
    '...rwwbrwwb.....',
    '...rwwwwwwb.....',
    '..rwwwwwwwwb....',
    '.rwwwwwwwwwwb...',
    '.rwkwkwwkwkwb...',
    '.rwwkwwwwkwwb...',
    '.rwkwkwwkwkwb...',
    '..rwwwwwwwwb....',
    '...rwwwwwwb.....',
    '................',
  ],
  PixelIcon.lock: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kgllllgk....',
    '....kl....lk....',
    '....kl....lk....',
    '....kl....lk....',
    '...kkkkkkkkkk...',
    '...kyyyyyyyyk...',
    '...kyyykkyyyk...',
    '...kyyykkyyyk...',
    '...kyyykkyyyk...',
    '...kooooooook...',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
  PixelIcon.floppy: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.knnllllllllnnk.',
    '.knnllkkllllnnk.',
    '.knnllkkllllnnk.',
    '.knnllllllllnnk.',
    '.knnnnnnnnnnnnk.',
    '.knwwwwwwwwwwnk.',
    '.knwggggggggwnk.',
    '.knwwwwwwwwwwnk.',
    '.knwggggggggwnk.',
    '.knwwwwwwwwwwnk.',
    '.knwwwwwwwwwwnk.',
    '.knnnnnnnnnnnnk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  PixelIcon.transfer: [
    '................',
    '......dd........',
    '......dGd.......',
    '..dddddGGd......',
    '..dGGGGGGGd.....',
    '..dGGGGGGGGd....',
    '..dGGGGGGGd.....',
    '..dddddGGd......',
    '......dGd.......',
    '......dd........',
    '.kkkkkkkkkkkkkk.',
    '.klllllllllllwk.',
    '.kllllllllllGlk.',
    '.kggggggggggggk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
};

/// Debug helper used by tests: every sprite is 16x16.
bool spritesAreValid() =>
    _sprites.values.every((rows) => rows.length == 16 && rows.every((r) => r.length == 16));
