import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
import fs from 'node:fs';
const [,, pageQ, out, timeoutS='600'] = process.argv;
const [page, query=''] = pageQ.split('?');
const head = fs.readFileSync(`${here}/scenes/head.html`,'utf8');
const src = fs.readFileSync(`${here}/scenes/${page}`,'utf8').replace('<!--#head-->', head);
fs.writeFileSync(`${here}/scenes/_${page}`, src);
const b = await chromium.launch({ args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--enable-webgl'] });
const p = await b.newPage();
p.on('console', m => console.log('[page]', m.text())); p.on('response', r => { if (r.status() >= 400) console.log('[404]', r.url()); }); p.on('pageerror', e => console.log('[err]', e.stack));
await p.goto(`http://localhost:8765/scenes/_${page}?${query}`);
const r = await p.waitForFunction(() => window.__done, null, { timeout: Number(timeoutS)*1000, polling: 1000 });
const d = await r.jsonValue();
fs.writeFileSync(out, Buffer.from(d.url.split(',')[1], 'base64'));
console.log(JSON.stringify({ms: d.ms, samples: d.samples, ...(d.info||{})}));
await b.close();
